spring.datasource.url=jdbc:postgresql://localhost:5432/repairs_db
spring.datasource.username=repairs_db_manager
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver