### GET ALL BOOKINGS
GET http://localhost:8080/booking


### POST A LIST OF BOOKINGS
POST http://localhost:8080/booking
Content-Type: application/json

[
  {
    "clientName": "Miahy",
    "clientPhone": "0327126921",
    "clientEmail": "miahy@gmail.com",
    "roomNumber": 8,
    "roomDescription": "Double Room",
    "date": "2026-03-15"
  }
]